/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 13 15:15:56 GMT 2017
 */

package io.protostuff;

import org.evosuite.shaded.org.mockito.Matchers;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.protostuff.ByteBufferInput;
import io.protostuff.ByteString;
import io.protostuff.CodedInput;
import io.protostuff.GraphCodedInput;
import io.protostuff.Schema;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.nio.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GraphCodedInput_ESTest extends GraphCodedInput_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CodedInput codedInput0 = new CodedInput((InputStream) null, true);
      GraphCodedInput graphCodedInput0 = new GraphCodedInput(codedInput0, 1569);
      byte[] byteArray0 = new byte[8];
      ByteString byteString0 = ByteString.copyFrom(byteArray0);
      ByteBuffer byteBuffer0 = byteString0.asReadOnlyByteBuffer();
      ByteBufferInput byteBufferInput0 = new ByteBufferInput(byteBuffer0, false);
      Schema<ByteBufferInput> schema0 = (Schema<ByteBufferInput>) mock(Schema.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(schema0).isInitialized(Matchers.<ByteBufferInput>any());
      // Undeclared exception!
      try { 
        graphCodedInput0.mergeObject(byteBufferInput0, schema0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("io.protostuff.GraphCodedInput", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      byteArray0[0] = (byte) (-1);
      CodedInput codedInput0 = new CodedInput(byteArray0, 0, (byte) (-1), true);
      GraphCodedInput graphCodedInput0 = new GraphCodedInput(codedInput0);
      Schema<CodedInput> schema0 = (Schema<CodedInput>) mock(Schema.class, new ViolatedAssumptionAnswer());
      int int0 = graphCodedInput0.readFieldNumber(schema0);
      assertEquals(2, codedInput0.getTotalBytesRead());
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CodedInput codedInput0 = new CodedInput(pipedInputStream0, true);
      GraphCodedInput graphCodedInput0 = new GraphCodedInput(codedInput0, 0);
      // Undeclared exception!
      try { 
        graphCodedInput0.updateLast((Object) null, pipedInputStream0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
