/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 14 11:44:53 GMT 2017
 */

package io.protostuff;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import io.protostuff.LimitedInputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.FileDescriptor;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LimitedInputStream_ESTest extends LimitedInputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Enumeration<InputStream> enumeration0 = (Enumeration<InputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      DataInputStream dataInputStream0 = new DataInputStream(sequenceInputStream0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(dataInputStream0);
      LimitedInputStream limitedInputStream1 = limitedInputStream0.limit(893);
      long long0 = limitedInputStream0.skip(2289L);
      assertEquals(0L, long0);
      
      int int0 = limitedInputStream1.available();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(mockFileInputStream0, 4310);
      byte[] byteArray0 = new byte[8];
      int int0 = limitedInputStream0.read(byteArray0, 4451, (-286));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      byteArray0[0] = (byte)1;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(byteArrayInputStream0, 1);
      int int0 = limitedInputStream0.read(byteArray0, (int) (byte)1, (int) (byte)70);
      assertArrayEquals(new byte[] {(byte)1, (byte)1, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0}, byteArray0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(pipedInputStream0, (-2100));
      byte[] byteArray0 = new byte[2];
      int int0 = limitedInputStream0.read(byteArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte)55;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(byteArrayInputStream0, (byte)55);
      int int0 = limitedInputStream0.read();
      assertEquals(8, byteArrayInputStream0.available());
      assertEquals(55, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(pipedInputStream0, (-2100));
      int int0 = limitedInputStream0.read();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      LimitedInputStream limitedInputStream0 = new LimitedInputStream(mockFileInputStream0, (-1943));
      LimitedInputStream limitedInputStream1 = limitedInputStream0.limit(3889);
      long long0 = limitedInputStream1.skip(3889);
      assertEquals(3889L, long0);
  }
}
